# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Programmieren\FLANC RAGE1.0\ui\FLANC_RAGE.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TabWidget(object):
    def setupUi(self, TabWidget):
        TabWidget.setObjectName("TabWidget")
        TabWidget.setWindowModality(QtCore.Qt.NonModal)
        TabWidget.resize(1100, 800)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(TabWidget.sizePolicy().hasHeightForWidth())
        TabWidget.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        TabWidget.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("d:\\Programmieren\\FLANC RAGE1.0\\ui\\flanc.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        TabWidget.setWindowIcon(icon)
        self.ranglisten = QtWidgets.QWidget()
        self.ranglisten.setObjectName("ranglisten")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.ranglisten)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem)
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")
        self.layout_v_serie = QtWidgets.QVBoxLayout()
        self.layout_v_serie.setObjectName("layout_v_serie")
        self.serie_btn = QtWidgets.QPushButton(self.ranglisten)
        self.serie_btn.setObjectName("serie_btn")
        self.layout_v_serie.addWidget(self.serie_btn)
        self.serie_cbb = QtWidgets.QComboBox(self.ranglisten)
        self.serie_cbb.setObjectName("serie_cbb")
        self.layout_v_serie.addWidget(self.serie_cbb)
        self.teams_btn = QtWidgets.QPushButton(self.ranglisten)
        self.teams_btn.setObjectName("teams_btn")
        self.layout_v_serie.addWidget(self.teams_btn)
        self.horizontalLayout1.addLayout(self.layout_v_serie)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout1.addItem(spacerItem1)
        self.layout_v_driver = QtWidgets.QVBoxLayout()
        self.layout_v_driver.setObjectName("layout_v_driver")
        self.name_btn = QtWidgets.QPushButton(self.ranglisten)
        self.name_btn.setObjectName("name_btn")
        self.layout_v_driver.addWidget(self.name_btn)
        self.name_cbb = QtWidgets.QComboBox(self.ranglisten)
        self.name_cbb.setObjectName("name_cbb")
        self.layout_v_driver.addWidget(self.name_cbb)
        self.all_drivers_btn = QtWidgets.QPushButton(self.ranglisten)
        self.all_drivers_btn.setObjectName("all_drivers_btn")
        self.layout_v_driver.addWidget(self.all_drivers_btn)
        self.horizontalLayout1.addLayout(self.layout_v_driver)
        self.verticalLayout_7.addLayout(self.horizontalLayout1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem2)
        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")
        self.layout_v_strecke = QtWidgets.QVBoxLayout()
        self.layout_v_strecke.setObjectName("layout_v_strecke")
        self.titel_strecke = QtWidgets.QLabel(self.ranglisten)
        self.titel_strecke.setObjectName("titel_strecke")
        self.layout_v_strecke.addWidget(self.titel_strecke)
        self.track_btn = QtWidgets.QPushButton(self.ranglisten)
        self.track_btn.setObjectName("track_btn")
        self.layout_v_strecke.addWidget(self.track_btn)
        self.track_cbb = QtWidgets.QComboBox(self.ranglisten)
        self.track_cbb.setEnabled(True)
        self.track_cbb.setObjectName("track_cbb")
        self.layout_v_strecke.addWidget(self.track_cbb)
        self.horizontalLayout2.addLayout(self.layout_v_strecke)
        spacerItem3 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout2.addItem(spacerItem3)
        self.layout_v_datum = QtWidgets.QVBoxLayout()
        self.layout_v_datum.setObjectName("layout_v_datum")
        self.titel_datum = QtWidgets.QLabel(self.ranglisten)
        self.titel_datum.setObjectName("titel_datum")
        self.layout_v_datum.addWidget(self.titel_datum)
        self.datum_btn = QtWidgets.QPushButton(self.ranglisten)
        self.datum_btn.setObjectName("datum_btn")
        self.layout_v_datum.addWidget(self.datum_btn)
        self.datum_cbb = QtWidgets.QComboBox(self.ranglisten)
        self.datum_cbb.setObjectName("datum_cbb")
        self.layout_v_datum.addWidget(self.datum_cbb)
        self.horizontalLayout2.addLayout(self.layout_v_datum)
        self.verticalLayout_7.addLayout(self.horizontalLayout2)
        spacerItem4 = QtWidgets.QSpacerItem(17, 17, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem4)
        self.all_races_btn = QtWidgets.QPushButton(self.ranglisten)
        self.all_races_btn.setObjectName("all_races_btn")
        self.verticalLayout_7.addWidget(self.all_races_btn)
        self.layout_v_alle_rennen = QtWidgets.QVBoxLayout()
        self.layout_v_alle_rennen.setObjectName("layout_v_alle_rennen")
        self.verticalLayout_7.addLayout(self.layout_v_alle_rennen)
        self.table = QtWidgets.QTableView(self.ranglisten)
        self.table.setObjectName("table")
        self.verticalLayout_7.addWidget(self.table)
        spacerItem5 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_7.addItem(spacerItem5)
        self.layout_h_exportieren = QtWidgets.QHBoxLayout()
        self.layout_h_exportieren.setObjectName("layout_h_exportieren")
        self.export_btn = QtWidgets.QPushButton(self.ranglisten)
        self.export_btn.setObjectName("export_btn")
        self.layout_h_exportieren.addWidget(self.export_btn)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_h_exportieren.addItem(spacerItem6)
        self.verticalLayout_7.addLayout(self.layout_h_exportieren)
        TabWidget.addTab(self.ranglisten, "")
        self.fahrerserienmanagement = QtWidgets.QWidget()
        self.fahrerserienmanagement.setObjectName("fahrerserienmanagement")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.fahrerserienmanagement)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.mgmt_fahrer_groupBox = QtWidgets.QGroupBox(self.fahrerserienmanagement)
        self.mgmt_fahrer_groupBox.setObjectName("mgmt_fahrer_groupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.mgmt_fahrer_groupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.layout_h_fahrer = QtWidgets.QHBoxLayout()
        self.layout_h_fahrer.setObjectName("layout_h_fahrer")
        self.mgmt_name_btn = QtWidgets.QPushButton(self.mgmt_fahrer_groupBox)
        self.mgmt_name_btn.setObjectName("mgmt_name_btn")
        self.layout_h_fahrer.addWidget(self.mgmt_name_btn)
        spacerItem7 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.layout_h_fahrer.addItem(spacerItem7)
        self.mgmt_name_cbb = QtWidgets.QComboBox(self.mgmt_fahrer_groupBox)
        self.mgmt_name_cbb.setObjectName("mgmt_name_cbb")
        self.layout_h_fahrer.addWidget(self.mgmt_name_cbb)
        self.verticalLayout_5.addLayout(self.layout_h_fahrer)
        spacerItem8 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem8)
        self.layout_v_fahrerdaten = QtWidgets.QVBoxLayout()
        self.layout_v_fahrerdaten.setObjectName("layout_v_fahrerdaten")
        self.layout_h_fahrerdaten = QtWidgets.QHBoxLayout()
        self.layout_h_fahrerdaten.setObjectName("layout_h_fahrerdaten")
        self.formLayout_fahrer_left = QtWidgets.QFormLayout()
        self.formLayout_fahrer_left.setObjectName("formLayout_fahrer_left")
        self.name_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.name_lbl.setObjectName("name_lbl")
        self.formLayout_fahrer_left.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.name_lbl)
        self.name_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.name_edit.setEnabled(False)
        self.name_edit.setObjectName("name_edit")
        self.formLayout_fahrer_left.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.name_edit)
        self.mail_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.mail_lbl.setObjectName("mail_lbl")
        self.formLayout_fahrer_left.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.mail_lbl)
        self.mail_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.mail_edit.setEnabled(False)
        self.mail_edit.setObjectName("mail_edit")
        self.formLayout_fahrer_left.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.mail_edit)
        self.layout_h_fahrerdaten.addLayout(self.formLayout_fahrer_left)
        spacerItem9 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.layout_h_fahrerdaten.addItem(spacerItem9)
        self.formLayout_fahrer_right = QtWidgets.QFormLayout()
        self.formLayout_fahrer_right.setObjectName("formLayout_fahrer_right")
        self.iracingnr_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.iracingnr_lbl.setObjectName("iracingnr_lbl")
        self.formLayout_fahrer_right.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.iracingnr_lbl)
        self.iracingnr_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.iracingnr_edit.setEnabled(False)
        self.iracingnr_edit.setObjectName("iracingnr_edit")
        self.formLayout_fahrer_right.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.iracingnr_edit)
        self.iracingname_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.iracingname_lbl.setObjectName("iracingname_lbl")
        self.formLayout_fahrer_right.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.iracingname_lbl)
        self.iracingname_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.iracingname_edit.setEnabled(False)
        self.iracingname_edit.setObjectName("iracingname_edit")
        self.formLayout_fahrer_right.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.iracingname_edit)
        self.layout_h_fahrerdaten.addLayout(self.formLayout_fahrer_right)
        self.layout_v_fahrerdaten.addLayout(self.layout_h_fahrerdaten)
        spacerItem10 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.layout_v_fahrerdaten.addItem(spacerItem10)
        self.serienteilnahme = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.serienteilnahme.setFont(font)
        self.serienteilnahme.setObjectName("serienteilnahme")
        self.layout_v_fahrerdaten.addWidget(self.serienteilnahme)
        self.layout_v_details_container = QtWidgets.QVBoxLayout()
        self.layout_v_details_container.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.layout_v_details_container.setSpacing(6)
        self.layout_v_details_container.setObjectName("layout_v_details_container")
        self.layout_v_fahrerdaten.addLayout(self.layout_v_details_container)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.layout_v_fahrerdaten.addItem(spacerItem11)
        self.team_details_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.team_details_lbl.setFont(font)
        self.team_details_lbl.setObjectName("team_details_lbl")
        self.layout_v_fahrerdaten.addWidget(self.team_details_lbl)
        self.layout_h_team_korr = QtWidgets.QHBoxLayout()
        self.layout_h_team_korr.setObjectName("layout_h_team_korr")
        self.formLayout_korr_left = QtWidgets.QFormLayout()
        self.formLayout_korr_left.setObjectName("formLayout_korr_left")
        self.teamname_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.teamname_lbl.setObjectName("teamname_lbl")
        self.formLayout_korr_left.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.teamname_lbl)
        self.teamname_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.teamname_edit.setEnabled(False)
        self.teamname_edit.setObjectName("teamname_edit")
        self.formLayout_korr_left.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.teamname_edit)
        self.korrekturdatum_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.korrekturdatum_lbl.setObjectName("korrekturdatum_lbl")
        self.formLayout_korr_left.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.korrekturdatum_lbl)
        self.korrekturper_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.korrekturper_edit.setEnabled(False)
        self.korrekturper_edit.setObjectName("korrekturper_edit")
        self.formLayout_korr_left.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.korrekturper_edit)
        self.korrekturgrund_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.korrekturgrund_lbl.setObjectName("korrekturgrund_lbl")
        self.formLayout_korr_left.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.korrekturgrund_lbl)
        self.korrekturgrund_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.korrekturgrund_edit.setEnabled(False)
        self.korrekturgrund_edit.setObjectName("korrekturgrund_edit")
        self.formLayout_korr_left.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.korrekturgrund_edit)
        self.startnummer_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.startnummer_edit.setEnabled(False)
        self.startnummer_edit.setObjectName("startnummer_edit")
        self.formLayout_korr_left.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.startnummer_edit)
        self.label = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.label.setObjectName("label")
        self.formLayout_korr_left.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.layout_h_team_korr.addLayout(self.formLayout_korr_left)
        spacerItem12 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.layout_h_team_korr.addItem(spacerItem12)
        self.formLayout_korr_right = QtWidgets.QFormLayout()
        self.formLayout_korr_right.setObjectName("formLayout_korr_right")
        self.starts_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.starts_lbl.setObjectName("starts_lbl")
        self.formLayout_korr_right.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.starts_lbl)
        self.starts_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.starts_edit.setEnabled(False)
        self.starts_edit.setObjectName("starts_edit")
        self.formLayout_korr_right.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.starts_edit)
        self.incs_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.incs_lbl.setObjectName("incs_lbl")
        self.formLayout_korr_right.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.incs_lbl)
        self.incs_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.incs_edit.setEnabled(False)
        self.incs_edit.setObjectName("incs_edit")
        self.formLayout_korr_right.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.incs_edit)
        self.points_lbl = QtWidgets.QLabel(self.mgmt_fahrer_groupBox)
        self.points_lbl.setObjectName("points_lbl")
        self.formLayout_korr_right.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.points_lbl)
        self.points_edit = QtWidgets.QLineEdit(self.mgmt_fahrer_groupBox)
        self.points_edit.setEnabled(False)
        self.points_edit.setFrame(True)
        self.points_edit.setObjectName("points_edit")
        self.formLayout_korr_right.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.points_edit)
        self.layout_h_team_korr.addLayout(self.formLayout_korr_right)
        self.layout_v_fahrerdaten.addLayout(self.layout_h_team_korr)
        self.verticalLayout_5.addLayout(self.layout_v_fahrerdaten)
        spacerItem13 = QtWidgets.QSpacerItem(20, 15, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem13)
        self.layout_h_save = QtWidgets.QHBoxLayout()
        self.layout_h_save.setSpacing(6)
        self.layout_h_save.setObjectName("layout_h_save")
        self.fahrerundteam_speichern_btn = QtWidgets.QPushButton(self.mgmt_fahrer_groupBox)
        self.fahrerundteam_speichern_btn.setObjectName("fahrerundteam_speichern_btn")
        self.layout_h_save.addWidget(self.fahrerundteam_speichern_btn)
        self.db_backup_btn = QtWidgets.QPushButton(self.mgmt_fahrer_groupBox)
        self.db_backup_btn.setObjectName("db_backup_btn")
        self.layout_h_save.addWidget(self.db_backup_btn)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.layout_h_save.addItem(spacerItem14)
        self.fahrer_loeschen_btn = QtWidgets.QPushButton(self.mgmt_fahrer_groupBox)
        self.fahrer_loeschen_btn.setObjectName("fahrer_loeschen_btn")
        self.layout_h_save.addWidget(self.fahrer_loeschen_btn)
        self.verticalLayout_5.addLayout(self.layout_h_save)
        self.verticalLayout_8.addWidget(self.mgmt_fahrer_groupBox)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_8.addItem(spacerItem15)
        self.mgmt_serie_groupBox = QtWidgets.QGroupBox(self.fahrerserienmanagement)
        self.mgmt_serie_groupBox.setObjectName("mgmt_serie_groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.mgmt_serie_groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.layout_h_serie_laden = QtWidgets.QHBoxLayout()
        self.layout_h_serie_laden.setObjectName("layout_h_serie_laden")
        self.mgmt_serie_btn = QtWidgets.QPushButton(self.mgmt_serie_groupBox)
        self.mgmt_serie_btn.setObjectName("mgmt_serie_btn")
        self.layout_h_serie_laden.addWidget(self.mgmt_serie_btn)
        spacerItem16 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.layout_h_serie_laden.addItem(spacerItem16)
        self.mgmt_serie_cbb = QtWidgets.QComboBox(self.mgmt_serie_groupBox)
        self.mgmt_serie_cbb.setObjectName("mgmt_serie_cbb")
        self.layout_h_serie_laden.addWidget(self.mgmt_serie_cbb)
        self.verticalLayout_4.addLayout(self.layout_h_serie_laden)
        self.layout_h_add_del_fahrer = QtWidgets.QHBoxLayout()
        self.layout_h_add_del_fahrer.setObjectName("layout_h_add_del_fahrer")
        self.layout_v_neue_serie = QtWidgets.QVBoxLayout()
        self.layout_v_neue_serie.setObjectName("layout_v_neue_serie")
        self.neue_serie_erstellen_lbl = QtWidgets.QLabel(self.mgmt_serie_groupBox)
        self.neue_serie_erstellen_lbl.setObjectName("neue_serie_erstellen_lbl")
        self.layout_v_neue_serie.addWidget(self.neue_serie_erstellen_lbl)
        self.neue_serie_erstellen_edit = QtWidgets.QLineEdit(self.mgmt_serie_groupBox)
        self.neue_serie_erstellen_edit.setObjectName("neue_serie_erstellen_edit")
        self.layout_v_neue_serie.addWidget(self.neue_serie_erstellen_edit)
        self.neue_serie_erstellen_btn = QtWidgets.QPushButton(self.mgmt_serie_groupBox)
        self.neue_serie_erstellen_btn.setObjectName("neue_serie_erstellen_btn")
        self.layout_v_neue_serie.addWidget(self.neue_serie_erstellen_btn)
        self.layout_h_add_del_fahrer.addLayout(self.layout_v_neue_serie)
        spacerItem17 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.layout_h_add_del_fahrer.addItem(spacerItem17)
        self.layout_v_serie_aendern = QtWidgets.QVBoxLayout()
        self.layout_v_serie_aendern.setObjectName("layout_v_serie_aendern")
        self.serie_name_aendern_lbl = QtWidgets.QLabel(self.mgmt_serie_groupBox)
        self.serie_name_aendern_lbl.setObjectName("serie_name_aendern_lbl")
        self.layout_v_serie_aendern.addWidget(self.serie_name_aendern_lbl)
        self.serie_name_aendern_edit = QtWidgets.QLineEdit(self.mgmt_serie_groupBox)
        self.serie_name_aendern_edit.setObjectName("serie_name_aendern_edit")
        self.layout_v_serie_aendern.addWidget(self.serie_name_aendern_edit)
        self.serie_name_aendern_btn = QtWidgets.QPushButton(self.mgmt_serie_groupBox)
        self.serie_name_aendern_btn.setObjectName("serie_name_aendern_btn")
        self.layout_v_serie_aendern.addWidget(self.serie_name_aendern_btn)
        self.layout_h_add_del_fahrer.addLayout(self.layout_v_serie_aendern)
        spacerItem18 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.layout_h_add_del_fahrer.addItem(spacerItem18)
        self.layout_v_serie_loeschen = QtWidgets.QVBoxLayout()
        self.layout_v_serie_loeschen.setObjectName("layout_v_serie_loeschen")
        self.serie_loeschen_lbl = QtWidgets.QLabel(self.mgmt_serie_groupBox)
        self.serie_loeschen_lbl.setObjectName("serie_loeschen_lbl")
        self.layout_v_serie_loeschen.addWidget(self.serie_loeschen_lbl)
        self.serie_loeschen_edit = QtWidgets.QLineEdit(self.mgmt_serie_groupBox)
        self.serie_loeschen_edit.setReadOnly(True)
        self.serie_loeschen_edit.setObjectName("serie_loeschen_edit")
        self.layout_v_serie_loeschen.addWidget(self.serie_loeschen_edit)
        self.serie_loeschen_btn = QtWidgets.QPushButton(self.mgmt_serie_groupBox)
        self.serie_loeschen_btn.setObjectName("serie_loeschen_btn")
        self.layout_v_serie_loeschen.addWidget(self.serie_loeschen_btn)
        self.layout_h_add_del_fahrer.addLayout(self.layout_v_serie_loeschen)
        self.verticalLayout_4.addLayout(self.layout_h_add_del_fahrer)
        self.verticalLayout_8.addWidget(self.mgmt_serie_groupBox)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem19)
        TabWidget.addTab(self.fahrerserienmanagement, "")
        self.hilfe = QtWidgets.QWidget()
        self.hilfe.setObjectName("hilfe")
        self.hilfe_ueber_text = QtWidgets.QTextEdit(self.hilfe)
        self.hilfe_ueber_text.setGeometry(QtCore.QRect(20, 100, 1051, 651))
        self.hilfe_ueber_text.setObjectName("hilfe_ueber_text")
        self.flanc_logo = QtWidgets.QLabel(self.hilfe)
        self.flanc_logo.setGeometry(QtCore.QRect(810, 20, 251, 71))
        self.flanc_logo.setObjectName("flanc_logo")
        TabWidget.addTab(self.hilfe, "")

        self.retranslateUi(TabWidget)
        TabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(TabWidget)

    def retranslateUi(self, TabWidget):
        _translate = QtCore.QCoreApplication.translate
        TabWidget.setWindowTitle(_translate("TabWidget", "FLANC Ranglistengenerator v1.0"))
        self.serie_btn.setText(_translate("TabWidget", "Lade Serie"))
        self.teams_btn.setText(_translate("TabWidget", "Saison Teams"))
        self.name_btn.setText(_translate("TabWidget", "Lade Fahrer*innen"))
        self.all_drivers_btn.setText(_translate("TabWidget", "Alle Fahrer*innen"))
        self.titel_strecke.setText(_translate("TabWidget", "Rangliste der Serie laden nach"))
        self.track_btn.setText(_translate("TabWidget", "Strecke"))
        self.titel_datum.setText(_translate("TabWidget", "oder nach"))
        self.datum_btn.setText(_translate("TabWidget", "Datum"))
        self.all_races_btn.setText(_translate("TabWidget", "Alle Rennen"))
        self.export_btn.setText(_translate("TabWidget", "Liste exportieren"))
        TabWidget.setTabText(TabWidget.indexOf(self.ranglisten), _translate("TabWidget", "Ranglisten"))
        self.mgmt_fahrer_groupBox.setTitle(_translate("TabWidget", "Fahrer*innenmanagement"))
        self.mgmt_name_btn.setText(_translate("TabWidget", "Fahrer*in laden"))
        self.name_lbl.setText(_translate("TabWidget", "Name"))
        self.mail_lbl.setText(_translate("TabWidget", "Mail"))
        self.iracingnr_lbl.setText(_translate("TabWidget", "iRacing Nr"))
        self.iracingname_lbl.setText(_translate("TabWidget", "iRacing Name"))
        self.serienteilnahme.setText(_translate("TabWidget", "Serienteilahme"))
        self.team_details_lbl.setText(_translate("TabWidget", "Team Details"))
        self.teamname_lbl.setText(_translate("TabWidget", "Team Name"))
        self.korrekturdatum_lbl.setText(_translate("TabWidget", "Korrektur per"))
        self.korrekturgrund_lbl.setText(_translate("TabWidget", "Korrektur Grund"))
        self.label.setText(_translate("TabWidget", "Startnummer"))
        self.starts_lbl.setText(_translate("TabWidget", "Korrektur Starts"))
        self.incs_lbl.setText(_translate("TabWidget", "Korrektur Incs"))
        self.points_lbl.setText(_translate("TabWidget", "Korrektur Points"))
        self.fahrerundteam_speichern_btn.setText(_translate("TabWidget", "Anpassungen speichern"))
        self.db_backup_btn.setText(_translate("TabWidget", "Datenbank Backup starten"))
        self.fahrer_loeschen_btn.setText(_translate("TabWidget", "Fahrer*in aus allen Serien und der Datenbank LÖSCHEN"))
        self.mgmt_serie_groupBox.setTitle(_translate("TabWidget", "Serienmanagement"))
        self.mgmt_serie_btn.setText(_translate("TabWidget", "Serien laden"))
        self.neue_serie_erstellen_lbl.setText(_translate("TabWidget", "Neue Serie erstellen"))
        self.neue_serie_erstellen_btn.setText(_translate("TabWidget", "Erstellen"))
        self.serie_name_aendern_lbl.setText(_translate("TabWidget", "Ausgewählte Serie Namen ändern"))
        self.serie_name_aendern_btn.setText(_translate("TabWidget", "Ändern"))
        self.serie_loeschen_lbl.setText(_translate("TabWidget", "Ausgewählte Serie löschen"))
        self.serie_loeschen_btn.setText(_translate("TabWidget", "LÖSCHEN"))
        TabWidget.setTabText(TabWidget.indexOf(self.fahrerserienmanagement), _translate("TabWidget", "Fahrer- und Serienmanagement"))
        self.hilfe_ueber_text.setHtml(_translate("TabWidget", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">FLANC Ranglistengenerator (RAGE v1.0 - &quot;Janeway&quot;)</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">1. Einleitung</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">RAGE ist ein in Python geschriebenes Programm für die FLANC. Damit können in erster Linie rasch Ranglisten generiert werden. Ebenfalls kann der Fahrerdatenbestand gepflegt werden. Die folgenden Kapitel erklären RAGE grunsätzlich, welche Daten nötig sind und wie die Funktionen in den Registern verwendet werden können. Am Ende beschreibt ein technisches Kapitel, welche Python Module verwendet werden.  </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Daten, die RAGE benötigt</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Die folgende Abbildung zeigt die Verzeichnisstruktur, wie sie zwingend zur Verfügung stehen muss. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/newPrefix/rage_verzeichnisstruktur.png\" /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Auf derselben Ebene, wie die EXE Datei, muss also ebenfalls die fahrer.json, sowie das Verzeichnis mit den jeweiligen Resultaten vorhanden sein. Auf der linken Seite ist ersichtlich, welche Struktur unter &quot;data&quot; nötig ist. Wichtig ist hier, dass pro Serie ein Verzeichnis erstellt wird und dieses den identischen Namen hat, wie im fahrer.json (siehe nächstes Kapitel).</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Die Fahrerdatenbank (fahrer.json)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Die folgende Abbildung zeigt die Struktur der fahrer.json. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/newPrefix/rage_fahrer_struktur.png\" /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Eine JSON Datei anstelle einer Datenbank wurde aus folgenden zwei Gründen umgesetzt: Es ist kein Datenbankserver nötig, es muss nur die EXE ausgeführt werden. In einer JSON sind die Daten mit einem geeigneten Editor einfach lesbar und können gegebenenfalls auch direkt verändert werden. Natürlich hat diese Lösung auch Nachteile. So sollte die EXE nicht von zwei Personen gleichezeitig genutzt und Daten verändert werden. Soll die fahrer.json direkt bearbeitet werden, muss dies unbedingt in einem geeigneten Editor passieren. Zu empfehlen sind die zwei gratis Programme Notepad++ oder Visual Studio Code. <span style=\" font-style:italic;\">Keinenfalls darf die fahrer.json mit Word geöffnet und gespeichert werden! </span>Vor grösseren Anpassungen (z. B. erstellen einer neuen Serie oder löschen von alten Serien) unbedingt von der fahrer.json eine Kopie erstellen.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Die JSON Struktur ist absichtlich flach und einfach gehalten. Die Daten befinden sich in einer Liste (Array), sichtbar durch die [ auf Zeile 1. Danach folgt pro Fahrer ein Dictionary, erkennbar durch die {. Darin befinden sich die nötigen Schlüssel-Werte-Paare. Die ersten drei Zeilen sind pro Fahrer einmal vorhanden. Danach folgen pro Serie die Paare.: </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- .Status (leer, also &quot;&quot; oder &quot;aktiv&quot; wenn aktiv in der Serie oder &quot;out&quot; wenn in der Serie, aber nicht mehr aktiv) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- .Team (Teamname in dieser Serie) </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- .TeamStKorr (Zahl falls nötig durch Teamwechsel oder ähnliches)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- .TeamIncKorr (Korrektur Incidents)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- .TeamPktKorr (Korrektur der Punkte)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- .TeamKorrDatum (wann wurde die Korrektur gemacht)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">- .TeamKorrGrund (Erklärung für später :-))</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"> </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Die Serie Bezeichnung vor dem Punkt, also z. B. <span style=\" font-style:italic;\">GT3 2021</span>.Status muss zwingend mit dem Verzeichnisnamen im RAGE/data übereinstimmen. War ein Fahrer oder Fahrerin in einer Serie gemeldet und hat er oder sie an mindestens einem Rennen teilgenommen, soll der Status immer entweder &quot;aktiv&quot; oder &quot;out&quot; sein. Nie sollte dann der Status leer bleiben. Grund: In der Teamwertung werden auch Punkte von Fahrern gewertet, welche den Status &quot;out&quot; haben. Wird der Fahrer aus der fahrer.json während der Serie gelöscht oder der Status auf &quot;&quot; gesetzt, werden seine Punkte nicht mehr berüchsichtigt. Zudem werden Ranglisten einzelner Rennen dann ev. leer Zeilen aufweisen, da die Fahrerangaben fehlen.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Die Team Korrekturen sind dals Zahl (integer) eingetragen, damit RAGE sie direkt verrechnen kann. Bei einem Teamwechsel können die Punkte nicht mitgenommen werden. Sie müssen daher beim Fahrer direkt als minus Zahl angegeben werden.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Das Datum und der Grund sind rein informativ. Das Datum muss daher kein vorgegebenes Format aufweisen.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Die iRacing Rennen (xxx.json)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Nach dem Rennen können im neuen iRacing UI die Ranglisten als JSON heruntergeladen werden. Ist diese Datei dann im richtigen Verzeichnis in RAGE/data/[Serie] abgelegt, steht sie in RAGE zur Auswertung zur verfügung. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">2. Register Ranglisten</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hier können rasch Ranglisten generiert und ins Excel exportiert werden. Als erstes muss dafür entweder eine Serie oder ein Fahrer oder Fahrerin geladen werden. Wird eine Serie geladen, steht die Serie-Rangliste direkt zur Verfügung und kann exportiert werden. Ein Klick auf &quot;Saison Teams&quot; generiert als nächstes die Rangliste der Teams dieser Saison. Mit einem weiteren Klick auf &quot;Export&quot; wird auch diese Rangliste exportiert und in dieselbe Datei &quot;RAGE Export.xlsx&quot; geschrieben. Mit vier Klicks wird somit eine Datei mit der Fahrer- und der Teamrangliste generiert :-)</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ist die Serie mit &quot;Lade Serie&quot; geladen, können ebenfalls einzelne Strecken der Serie nach Name oder nach Datum angezeigt und exportiert werden.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mit &quot;Lade Fahrer*innen&quot; kann eine einzelne Person danach ausgewählt werden. Die Rennergebnisse werden dann Serien unabhängig dargestellt. Es ist daher rasch sichtbar, welche Rennen in welcher Serie mit welchen Ergebnissen gefahren wurde. Praktisch für\'s kommentieren und erstellen weiterer Statistiken.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mit &quot;Alle Fahrer*innen&quot; wird die ganze fahrer.json ausgegeben. Praktisch z. B. für SRA TV, welche pro Fahrer auch die iRacingNr und iRacing Namen benötigen. Die Korrekturen pro Serie können im Excel nachträglich dabei oft gelöscht werden, um die Tabelle nicht zu überladen.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">&quot;Alle Rennen&quot; zeigt, wie der Name sagt, alle Rennen dieser Serien an. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">3. Register Fahrer- und Serienmanagement</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">In diesem Register können bestehende Fahrerinnen und Fahrer angepasst und gelöscht, sowie neue erfasst werden. Das gleiche ist mit Serien möglich. Es ist zu beachten, dass hier mit ein paar Klicks rasch viele Daten gelöscht in der Datei fahrer.json gelöscht werden können. Daher sollte regelmässig, am besten vor solchen Mutationen ein Backup der fahrer.json erstellt werden. Dies ist mit dem Button <span style=\" font-style:italic;\">Datenbank Backup starten</span> einfach zu erledigen. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">WICHTIG:</span> Werden pro Tag mehr als ein Backup erstellt, überschreibt sich die Datei mit demselben Datum!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Bestehende Fahrerin oder bestehenden Fahrer anpassen</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mit einem Klick auf <span style=\" font-style:italic;\">Fahrer*in laden </span>stehen im Dropdownmenü alle bekannten Fahrer*innen zur Verfügung. Wird eine Person ausgewählt, ist Name, Mail, sowie iRacingNr. und iRacing Name ersichtlich. Ebenfalls werden pro Person die in RAGE bekannten Serien (gemäss fahrer.json) aufgelistet. So ist rasch ersichtlich, wer in welcher Serie mitfährt oder eingetragen war.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">WICHTIG: </span>Fahrer*innen, die einmal in einer Serie gefahren sind, aber während der Saison aufgehört haben, sollten mit &quot;out&quot; gekenntzeichnet werden. Die Checkbox bei der Serie muss aber aktiv bleiben. Nur so zählen die Punkte für die Teamrangiste noch mit. Ansonsten fehlen diese.  </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Ebenfalls WICHTIG:</span> Unter<span style=\" font-style:italic;\"> Team Details</span> können Angaben oder Korrekturen erfasst werden. Bitte pro Serie einmal speichern (also, <span style=\" font-style:italic;\">Team Details</span> klicken, unten Angaben anpassen, <span style=\" font-style:italic;\">Anpassungen speichern</span>. Erst danach eine weitere Serie bearbeiten). RAGE speichert nur, was in dem Moment angezeigt wird!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Neue Fahrerin oder Fahrer erfassen</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Neue Personen können erfasst werden, in dem anstelle eines Namens auf <span style=\" font-style:italic;\">1 neuer Eintrag</span> im Dropdown geklickt wird. Die leeren Felder können danach ausgefüllt und auf <span style=\" font-style:italic;\">Anpassung speichern</span> geklickt werden. Zuordnungen zu Serien sind hier ebenfalls direkt möglich. Bitte beachtet nur, dass auch hier pro<span style=\" font-style:italic;\"> Team Detail </span>einmal gespeichert werden muss. RAGE speichert nur, was in dem Moment sichtbar ist. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">WICHTIG:</span> Damit die Person nach dem Speichern im Dropdown als Name ersichtlich ist, müssen die Daten mit Fahrer*innen laden neu geholt werden. Beginnt ein Name mit einem kleinen Buchstaben ist er ganz unten ersichtlich.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Fahrer*innen aus allen Serien und der Datenbank löschen</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Tut, was es sagt. Es wird zur Sicherheit nochmals eine Bestätigung verlangt, bevor die Löschung effektiv erfolgt. Mach vorher bei Bedarf ein Backup der fahrer.json Datei. Weil, gelöscht ist gelöscht!</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Serienmanagement</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Hier können Serien erstellt und gelöscht werden. Zudem ist es auch möglich, bestehende Seriennamen anzupassen. Egal was angepasst wird, immer daran denken, das Verzeichnis unter <span style=\" font-style:italic;\">data </span>(siehe Daten die RAGE benötigt) anzupassen.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">4. Wenn Probleme auftreten (Kleines Troubleshooting)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Im folgenden werden ein paar Situationen genannt, die auftreten können, und die mögliche Ursache, sowie Lösung.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Problem: RAGE läst sich nicht starten.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mögliche Ursache: Das Programm wurde bereits durch eine andere Person geöffnet.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lösung: Warten, bis die andere Person das Programm geschlossen hat ;-)</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Problem: Rennen / Punkte werden in RAGE nicht angezeigt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mögliche Ursache: xx.json von iRacing nicht oder im falschen Ordner abgelegt</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lösung: Mit &quot;Lade Serie&quot; die Daten laden und kontrollieren, ob unter &quot;Strecke&quot; das neuste Rennen ersichtlich ist. Wenn nein, fehlt die Datei im Serien Ordner. Wenn ja, hat iRacing ev. die Struktur in xxx.json geändert. Dann muss das Programm angepasst werden.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Problem: Aktuelle Rangliste gibt bei Punkten überall nur 0 an</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mögliche Ursache: Die .json Resultate Datei wurde zu schnell nach dem Rennen in iRacing heruntergelanden. Dann kommt es zu diesem Effekt, weil die Punktezuordnung wohl noch nicht abgeschlossen war.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lösung: Datei nochmals in iRacing herunterladen und testen.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Problem: In einem Team fehlen plötzlich Punkte / Incs / Starts einer Fahrerin oder  eines Fahrers</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mögliche Ursache: Bei einer Fahrerin oder einem Fahrer wurden im Fahrer*innenmanagement die Checkbox bei der Serienteilnahme deaktiviert. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lösung: Checkbox bei der Serie wieder aktivieren. Dahinter den Status von <span style=\" font-style:italic;\">aktiv</span> auf <span style=\" font-style:italic;\">out</span> umstellen. So erscheint die Person nicht mehr auf den Saisonranglisten, die Punkte werden aber beim Team noch dazu gezählt.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Problem: Im Fahrer*innenmanagement unter den Team Details werden Daten teilweise nicht gespeichert</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mögliche Ursache: Du passt bei mehreren Serien Details Daten an, ohne dazwischen zu speichern</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lösung: RAGE kann immer du das speichern, was ersichtlich ist. Die nächste Abbildung verdeutlicht dies. Wenn du in der F3 und der GT3 unter <span style=\" font-style:italic;\">Team Details</span> Anpassungen gemacht hast, wird nur die von der GT3 gespeichert, weil nur die in dem Moment ersichtlich sind, wenn du auf <span style=\" font-style:italic;\">Anpassungen speichern</span> klickst. </p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><img src=\":/newPrefix/rage_team_details_speichern.png\" /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Problem: Neu erfasste Fahrerin oder Fahrer ist nicht in der Dropdownliste ersichtlich</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Mögliche Ursache: Die Person ist erfasst, aber es wird noch die vorherige Liste, in der sie nicht vorhanden war, angezeigt.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Lösung: Auf <span style=\" font-style:italic;\">Fahrer*in laden</span> klicken, um die Daten neu zu laden.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt; font-weight:600;\">5. Technische Informationen zu RAGE</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">RAGE ist in Python 3.6 gechrieben und benötigt folgende Module.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Pandas</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Die eingelesenen JSON Daten werden in ein Pandas Dataframe eingelsen. Deshalb startet alles jeweils mit einem &quot;xxx laden&quot; Button. Danach kann mit weiteren Buttons den Datenbestand gefilter und als Liste ausgegeben werden. Dies Lösung ist nicht die Beste, funktioniert aber soweit ganz gut. Vorallem können so Daten leicht ins Excel exportiert werden.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Die Funktionen, welche die Daten aufbereiten sind im Modul (Verzeichnis) &quot;aufbereitung&quot; und sind in input.py, output.py und work.py eingeteilt. </p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">openypxl</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Um die Excel Exporte wunschgemäss formatieren zu können, wird openpyxl verwendet. Die Formatierung ist im Modul (Verzeichnis) &quot;excel&quot;. Die formatexport.py formatiert die einzelnen Listen. Die writeexport.py schreibt diese dann effektiv ins Excel. Hier werden nur noch die Spaltenbreiten mitgegeben. Da dies teilweise noch statisch hinterlegt ist, dann es sein, dass hier später Anpassungen nötig werden.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">PyQt5 und Qt</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Um ein einigesmassen ansprechendes GUI zu erstellen wurde PyQt5 verwendet. Die Dateien befinden sich im Modul (Verzeichnis) &quot;ui&quot;. Die FLANC_RAGE.ui wurde mit dem Qt Designer generiert und als Ui_FLANC_RAGE.py kompiliert. Ebenfalls vorhanden und kompiliert ist die Qt_GUI.qrc als Qt_GUI_rc.py. Damit werden Ressourden wie Bilder zur Verfügung gestellt. Das Layout wird in der app.py als Modul implementiert und kann daher problemlos immer wieder neu kompiliert werden, falls Änderungen im GUI nötig sind. Einzig muss in der Ui_FLANC_RAGE.py in der untersten Zeile der Eintrag:</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">import Qt_GUI_rc.py in</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">from ui import Qt_GUI_rc.py geändert werden.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Ebenfalls im &quot;ui&quot; Verzeichnis müssen sich alles Grafiken befinden.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">pyinstaller</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Das Programm wird mit pyinstaller. Die Parameter dazu befinden sich in der Datei wichtig.txt</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-weight:600;\">Versionsverlauf</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 1.0 - &quot;Janeway&quot;: Bugfixes, stabile Version</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 0.9 - &quot;Crusher&quot;: Serienmanagement und Backup</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 0.8 - &quot;Troi&quot;: Fahrer*innen Management</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Version 0.7 - &quot;Yar&quot;: Nur Ranglisten generieren</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Das Programm wird ab der Version 1.0 unter Github im Repository von &quot;thierwaechter/RAGE&quot; ersichtlich sein.</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.flanc_logo.setText(_translate("TabWidget", "<html><head/><body><p><img src=\":/newPrefix/FLANC_Rechteck_250.jpg\"/></p></body></html>"))
        TabWidget.setTabText(TabWidget.indexOf(self.hilfe), _translate("TabWidget", "Hilfe / Über"))
from ui import Qt_GUI_rc
